//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKTServiceLib.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KKTServiceLib.Shared.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При проверке данных агента в предмете расчета {0} возникли следующие ошибки.
        /// </summary>
        public static string AgentInPositionValidationError {
            get {
                return ResourceManager.GetString("AgentInPositionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При проверке данных агента возникли следующие ошибки.
        /// </summary>
        public static string AgentPropertiesRequirementValidationError {
            get {
                return ResourceManager.GetString("AgentPropertiesRequirementValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр &apos;{0}&apos; должен отсутствовать для агента с типом &apos;{1}&apos;.
        /// </summary>
        public static string AgentPropertyIsNotRequiredValidationError {
            get {
                return ResourceManager.GetString("AgentPropertyIsNotRequiredValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр &apos;{0}&apos; обязателен для агента с типом &apos;{1}&apos;.
        /// </summary>
        public static string AgentPropertyIsRequiredValidationError {
            get {
                return ResourceManager.GetString("AgentPropertyIsRequiredValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Штрихкод с типом &apos;{0}&apos; имеет неверный формат.
        /// </summary>
        public static string BarcodeValueFormatError {
            get {
                return ResourceManager.GetString("BarcodeValueFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последовательность &apos;{0}&apos; содержит элементы со следующими ошибками.
        /// </summary>
        public static string ComplexObjectCollectionValidationError {
            get {
                return ResourceManager.GetString("ComplexObjectCollectionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не может быть пустым.
        /// </summary>
        public static string ComplexObjectCollectionValidationError_ContainsNull {
            get {
                return ResourceManager.GetString("ComplexObjectCollectionValidationError_ContainsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент {0}: .
        /// </summary>
        public static string ComplexObjectCollectionValidationError_Index {
            get {
                return ResourceManager.GetString("ComplexObjectCollectionValidationError_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр &apos;{0}&apos; имеет следующие ошибки.
        /// </summary>
        public static string ComplexObjectValidationError {
            get {
                return ResourceManager.GetString("ComplexObjectValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата в параметре &apos;{0}&apos; должна лежать в диапазоне {1} - {2}.
        /// </summary>
        public static string DateTimeError {
            get {
                return ResourceManager.GetString("DateTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата в параметре &apos;{0}&apos; введена некорректно.
        /// </summary>
        public static string DateTimeFormatError {
            get {
                return ResourceManager.GetString("DateTimeFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр &apos;{0}&apos; должен иметь значение не менее {1} и не более {2}.
        /// </summary>
        public static string DigitRangeValuesError {
            get {
                return ResourceManager.GetString("DigitRangeValuesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фискальный документ выбранного типа не может иметь параметры чека коррекции.
        /// </summary>
        public static string IsNotCorrectionReceiptError {
            get {
                return ResourceManager.GetString("IsNotCorrectionReceiptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество элементов в последовательности &apos;{0}&apos; должно быть не менее {1}.
        /// </summary>
        public static string MinLengthError {
            get {
                return ResourceManager.GetString("MinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр &apos;{0}&apos; должен быть равен следующим значениям: {1}.
        /// </summary>
        public static string MustBeEqualError {
            get {
                return ResourceManager.GetString("MustBeEqualError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр &apos;{0}&apos; должен быть пустым.
        /// </summary>
        public static string MustBeNullError {
            get {
                return ResourceManager.GetString("MustBeNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одна или несколько строк в последовательности &apos;{0}&apos; имеют неверный формат: {1}.
        /// </summary>
        public static string RegularExpressionCollectionValidationError {
            get {
                return ResourceManager.GetString("RegularExpressionCollectionValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр &apos;{0}&apos; не может быть пустым.
        /// </summary>
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр &apos;{0}&apos; имеет неверный формат.
        /// </summary>
        public static string StringFormatError {
            get {
                return ResourceManager.GetString("StringFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр &apos;{0}&apos; должен содержать не более {1} символов.
        /// </summary>
        public static string StringMaxLengthError {
            get {
                return ResourceManager.GetString("StringMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр &apos;{0}&apos; должен содержать не менее {1} символов.
        /// </summary>
        public static string StringMinLengthError {
            get {
                return ResourceManager.GetString("StringMinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр &apos;{0}&apos; должен содержать не менее {1}  и не более {2} символов.
        /// </summary>
        public static string StringRangeLengthError {
            get {
                return ResourceManager.GetString("StringRangeLengthError", resourceCulture);
            }
        }
    }
}
